cmd/evm/internal/t8ntool: add missing BaseFee field to ExecutionResult struct
And carry this through to assignment at the Apply method

This solves what felt like a big issue using core-geth's evm
with retesteth, which kept complaining as:

WARNING: tool vs retesteth basefee disagree: 0 vs 10
makeRPCError Invalid block: base fee not correct! Expected: '10', got: '0'
Finishing retesteth run
*** Total Tests Run: 0

Error: Invalid block: base fee not correct! Expected: '10', got: '0' (stRandom/randomStatetest153, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: )

--------
TestOutputHelper detected 1 errors during test execution!
/home/ia/dev/ethereum/retesteth/retesteth/TestOutputHelper.cpp(222): error: in 'GeneralStateTests/stRandom'

Date: 2022-11-11 08:02:47-08:00
Signed-off-by: meows <b5c6@protonmail.com>